package uk.co.bns.warehouse_api.config;

import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import uk.co.bns.warehouse_api.entity.User;
import uk.co.bns.warehouse_api.repository.UserRepository;

/**
 * Creates the very first login on an empty database - "Dan Cheetham" with a
 * fixed temporary password, which MUST be changed immediately from Settings >
 * Users after first login. Runs at actual application startup (not baked into
 * a migration) specifically so the password hash is generated by the real
 * PasswordEncoder bean that will later verify it, rather than a hash computed
 * some other way that might not be byte-for-byte compatible.
 */
@Component
@RequiredArgsConstructor
public class FirstUserSeeder implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(FirstUserSeeder.class);
    private static final String DEFAULT_TEMP_PASSWORD = "ChangeMe123!";

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    public void run(ApplicationArguments args) {
        if (userRepository.count() > 0) return;

        User user = new User();
        user.setName("Dan Cheetham");
        user.setPasswordHash(passwordEncoder.encode(DEFAULT_TEMP_PASSWORD));
        userRepository.save(user);

        log.warn("No users existed - created 'Dan Cheetham' with temporary password '{}'. "
                + "Change this immediately via Settings > Users.", DEFAULT_TEMP_PASSWORD);
    }
}
